// Action types
const MODULE_NAME = "USER_ACTION_";


export const SET_PROCESSING = MODULE_NAME + "_SET_PROCESSING";
export const SET_USER_DATA = MODULE_NAME + "_SET_USER_DATA";
export const SET_AUTHENTICATED = MODULE_NAME + "_SET_AUTHENTICATED";
export const SET_AUTHENTICATED_USERDATA = MODULE_NAME + "_SET_AUTHENTICATED_USERDATA";
export const SET_TOKEN = MODULE_NAME + "_SET_TOKEN";


